### ISSUE TITLE
Contributors preferences

### ISSUE THREAD

**Issue by douweschulte** [douweschulte/pdbtbx#75]
I added a CITATON.cff file to help other people cite the software and recognise all contributors. If there is anything you would like to add/change or if you do not want to be listed please let me know. 
@TianyiShi2001 @DocKDE

current authors section:
```yaml
authors:
  - affiliation: Utrecht University
    family-names: Schulte
    given-names: Douwe
    orcid: https://orcid.org/0000-0003-0594-0993
  - family-names: Shi
    given-names: Tianyi
  - name: DocKDE
 ```
